### ISSUE TITLE
Check for IPv6 address and false positives with ipv4

### ISSUE THREAD

**Issue by devikasondhi** [daveoncode/python-string-utils#5]
The is_ip() seems to be missing on checks for the validity of ipv6 addresses, for instance, `"3ffe::1"`.
Also, for ipv4 address, the validator unexpectedly returns True for the invalid address `"016.016.016.016"`

**Comment by devikasondhi** [comment]
I think, the range limit should also be handled in the octets. `'900.200.100.75'` is being treated as valid by the is_ip() function

**Comment by daveoncode** [comment]
Fixed with latest release: 1.0.0
See changelog: https://github.com/daveoncode/python-string-utils/blob/master/CHANGELOG.md
