### ISSUE TITLE
Double quotes in email address

### ISSUE THREAD

**Issue by devikasondhi** [daveoncode/python-string-utils#7]
RFC 5322 (https://tools.ietf.org/html/rfc5322) allows usage of double quotes in email, such as `"test@test"@example.com`. However, the is_email() function does not account for this.

**Comment by devikasondhi** [comment]
Also, the local part for the email address is expected to be <=64 bytes (https://tools.ietf.org/html/rfc3696#page-7). However, the current validator does not check for this.
`is_email('john56789.john56789.john56789.john56789.john56789.john56789.john5@example.com') ` returns `True`

**Comment by daveoncode** [comment]
Fixed with latest release: 1.0.0
See changelog: https://github.com/daveoncode/python-string-utils/blob/master/CHANGELOG.md
