### ISSUE TITLE
List of values is also a valid json

### ISSUE THREAD

**Issue by devikasondhi** [daveoncode/python-string-utils#8]
The `is_json` function only seems to support a collection of name-value pairs. However, an ordered list of values is also a valid json format (http://json.org/) now, which the validator does not take into account.

For instance, `is_json('{"abcs"}') `should return `True`, which is not currently the case.

**Comment by daveoncode** [comment]
Fixed with latest release: 1.0.0
See changelog: https://github.com/daveoncode/python-string-utils/blob/master/CHANGELOG.md
